name: lint
on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウトします
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # commitlintを行います
      - uses: wagoid/commitlint-github-action@v2
